### ISSUE TITLE
Implement iterator for Queues

### ISSUE THREAD

**Issue by mrniko** [JCTools/JCTools#124]
https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpscChunkedArrayQueue.java#L145

Related to https://github.com/netty/netty/issues/5581

**Comment by nitsanw** [comment]
Can you expand on why this is functionality you need from a queue?

**Comment by mrniko** [comment]
I need to get all queue values in some cases.

**Comment by nitsanw** [comment]
I understand you have no time to elaborate, sadly I am also short on time. Iterators have not thus far been a feature most users of JCTools can do without. Developing it comes at a price of time, effort, and maintenance. Unless you present a good case for it I don't think it will happen.

**Comment by guidomedina** [comment]
@mrniko 

Most queues offer drain functionality but such thing can be emulated by consuming the queue hence if this is the case then there is no need for iterator.

An iterator for a circular, linked arrays and concurrent queue can be quite a challenge TBH.

**Comment by nitsanw** [comment]
This is not super hard if we are willing to accept on consumer is allowed to iterate. You'll need an iterator similar to the drain loop, but without moving consumerIndex and shifting the buffers. Open to PRs.

**Comment by nitsanw** [comment]
In the interest of enabling #60 it would be good to provide a limited iterator implementation such that:
 1. Remove for the tail works, but otherwise does not work.
 2. Iterator is assumed to have similar guarantees to size(), in the sense that concurrent modification can lead to inconsistent results.
 3. Iterator is an extended peek mechanism.

This is an easy picking for someone looking to cut their teeth, so PRs welcome, one queue at a time please.

**Comment by Scottmitch** [comment]
Is there any preference to implementing this vs. just `remove` (limited to the consumer thread)? I'm interested in having the capability to remove from MPSC queues to prevent object references from being retained and prevent GC in some async use cases. The advantage of just implementing `remove` is avoiding iterator creation and having to worry about complexity of iteration vs. the more general usage provided by an Iterator.

**Comment by nitsanw** [comment]
@Scottmitch How do you mean "just remove"? I assume you are refferring to `boolean remove(Object o)`
The issue with removing anything but the consumerIndex element (the next polled element) is that it leaves a gap in the underlying queue that needs handling. In a linked queue you can patch this gap, by dropping the node, but in an array backed data structure the `remove` will require another approach. Here's some thoughts on the matter (a cup of coffee worth, I'll charge it to your account ;)):
 - a TOMBSTONE element -> changes to offer/poll methods which will need to handle the TOMBSTONE as something to write/skip over. This will add some overhead which will be noticeable in the SPSC case at the very least. A compromise might be to provide a user defined TOMBSTONE element which is to be used by the queue to replace the element removed, but will not get special treatment in poll/offer implying for instance that a queue full of TOMBSTONE elements is still full, and that poll can return a TOMBSTONE. This is relatively easy to implement, but breaks the Queue specification.
 - a copy left on remove -> O(n) operation, but at the end of it the queue is back to 'normal'. Since remove is O(n) in any case, this may be a reasonable approach. I'm not very keen on it, but at least it does not add complexity to other methods in the single consumer case (in the multi-consumer case it might).
 - if the queue is not FIFO you can implement `remove` by swapping the removed element for the head element. This is a neat solution, but only suitable where FIFO is not required.

**Comment by Scottmitch** [comment]
@nitsanw - Yes I mean `remove(Object o)`. Currently I am interested in the `Linked` variants, and I have a PR pending so need need to charge for now 😜 .

The ideas you list above for the array based implementations are interesting and in general it would be interesting to profile 1 and 2. I see the appeal for the "user defined TOMBSTONE" but violating the queue spec seems a bit heavy handed. My preference would be to avoid changing the usage pattern of the queue in the event a user decides to call the `remove` method, and it may not be possible to alter the usage pattern depending on the code structure.

**Comment by nitsanw** [comment]
Iterator now supported for the array backed queues with https://github.com/JCTools/JCTools/commit/214133a2c7204426acc9fbb6f1242eaf3785659e

**Comment by nitsanw** [comment]
Closing this ticket, interested parties can open tickets for the remaining queues.
