### ISSUE TITLE
Review BaseMpscLinkedArrayQueue.java

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#134]
Nice trick with the index.

[L182](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/BaseMpscLinkedArrayQueue.java#L182) the buffer parameter is not used

[L198](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/BaseMpscLinkedArrayQueue.java) // the result 3 means resize & return true, looks misleading now

However, I'm not sure about updating the producer mask/buffer:
1. two threads enter offer(), thread 1 reads producerMask
2. thread 2 detects it needs to resize and enters into resize and updates the producerMask
3. thread 1 resumes and reads producerBuffer, enters the offerSlowPath() and getCurrentBufferCapacity() returns a value for the old producerMask but new buffer

It is also possible that producerMask/producerBuffer is written/read in non-program order and the step 3 may calculate with an old mask and new buffer.

I don't know if this is a benign data race or not. I'd access producerBuffer field lv/so and derive mask from its length instead of having that as a separate field.

**Comment by nitsanw** [comment]
Since there's multiple producers all mutable producer fields are in risk of concurrent change. The loaded buffer/mask are valid for the given index if they are loaded between a read and a successful CAS of the index. Since mutating these fields requires a successful CAS I feel this is safe.
The only other mutated field is the producerLimit, which is monotonically increasing and can tolerate the error I think.
