### ISSUE TITLE
How does relaxedOffer work for an MpscUnboundedArrayQueue?

### ISSUE THREAD

**Issue by alexandru** [JCTools/JCTools#137]
Seeing in the README that you encourage people to open GitHub issues for questions, here's a newbie one :-)

Can `relaxedOffer` return `false` for a `MpscUnboundedArrayQueue`?

I don't necessarily understand its semantics vs normal `offer`. From my understanding, these queues work well because the consumer isn't contending with the producers, same as the `j.u.c.ConcurrentLinkedQueue` we know and love, which means that even plain `offer` should sometimes return `false` without the queue being full, as the producers don't have clear visibility into what the consumer does. Or am I missing something?

So my problem is that I want to use that `false` result to detect and thrown an overflow exception and I don't care for that measurement to be super precise. So can I safely use `relaxedOffer` with both `MpscUnboundedArrayQueue` and `MpscChunkedArrayQueue`?

**Comment by nitsanw** [comment]
"plain offer should sometimes return false without the queue being full" - This is breaking the Queue interface contract:
"Inserts the specified element into this queue if it is possible to do so immediately without violating capacity restrictions." -> false iff queue is full -> if queue is unbounded ALWAYS return true.
What you are describing requires the offer method to return a status indicating the sort of failure it had. This has been done in MpscArrayQueue for instance:
https://github.com/JCTools/JCTools/blob/330b16178fea45223693936a52d686a8ae4585c8/jctools-core/src/main/java/org/jctools/queues/MpscArrayQueue.java#L258-L258
This is not supported by the Unbounded or Chunked queues.
The relaxedOffer contract allows the producer to fail when the queue is not full, and could be used to the purpose you describe. In JCTools so far it is used to allow SPMC and MPMC queues to ignore the queue full criteria when trying to offer. I've not chosen to make it also fail on contended CAS, but that can be easily implemented. Sadly the API choice here makes the failure opaque to users, since relaxedOffer/Poll also return a boolean and not an int/enum.
Let me know if you need further details.

**Comment by alexandru** [comment]
So I understand what you're saying, it's fine, thanks for the info.

To be clear, I don't want `relaxedOffer` to ever return `false` for unbounded queues, although I can see myself using `failFastOffer`.

Thanks,
