### ISSUE TITLE
Build generates atomic queues too many times

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#189]
Running mvn clean install results in generating the queues more than once.

**Comment by kay** [comment]
It's not just the generation of queues, looking at build log it's also things like javadoc. The second execution of these things is caused by the `maven-bundle-plugin` which the used version rebuilds everything again.

See https://issues.apache.org/jira/browse/FELIX-4882 and https://stackoverflow.com/questions/31231453/when-using-bundle-packaging-with-maven-bundle-plugin-goals-are-executed-twice
