### ISSUE TITLE
Message/consumer affinity in SPMC queues

### ISSUE THREAD

**Issue by richardstartin** [JCTools/JCTools#200]
Is there a way to implement message to consumer affinity for SPMC queues in this library? The semantics of the queue I have in mind are similar to Kafka: messages offered to a partitioned queue are hashed modulo the number of consumers to choose which partition and therefore consumer receives the message. This hash function should be configurable to only depend on, say, one or two fields of the message (in Kafka there is a concept of a message key which is used for this purpose.) The queue is FIFO per partition.

- Is this currently possible in JCTools?
- If not, would this feature be a welcome addition to this library?

**Comment by nitsanw** [comment]
This can be implemented on top of SPSC queues (or SPMC queues), but is not a JCTools feature. The problem here is not so much the implementation but the introduction of new and exciting API to the mix. JCTools currently offers j.u.Queue and it's own MessagePassingQueue. What you describe can implement this API, but would do so with different semantics, so would be a false pretense... Consider for instance the implications for size()/isEmpty() from a consumer POV. Is size computed for the container or for the consumer? this strikes me as a brittle thing to do.
Does this make sense?

**Comment by richardstartin** [comment]
That does make sense. Is that a “doesn’t fit in this library?”

**Comment by nitsanw** [comment]
I think so, sorry :(
