### ISSUE TITLE
NonBlockingHashMap remove bug

### ISSUE THREAD

**Issue by fvlad** [JCTools/JCTools#205]
Hi. I was playing with NonBlockingHashMap and found that removes can return one items more than once when executed concurrently. Here is the test sample:

    @Test
    public void testMap() throws Exception {
        final ExecutorService executor = Executors.newFixedThreadPool(32);

        final ConcurrentMap<String, String> map = new NonBlockingHashMap<>();
        final String key = UUID.randomUUID().toString();

        final int numberOfIterations = 10_000;
        final CountDownLatch latch = new CountDownLatch(numberOfIterations);

        CopyOnWriteArrayList<String> addedList = new CopyOnWriteArrayList<>();
        CopyOnWriteArrayList<String> removedList = new CopyOnWriteArrayList<>();

        for (int i = 0; i < numberOfIterations; i++) {
            if (i % 2 == 0) {
                executor.submit(() -> {
                    String added = UUID.randomUUID().toString();
                    map.put(key, added);

                    addedList.add(added);

                    latch.countDown();
                });
            } else {
                executor.submit(() -> {
                    String removed = map.remove(key);

                    if (removed != null) {
                        removedList.add(removed);
                    }

                    latch.countDown();
                });
            }
        }

        assertTrue(latch.await(5, TimeUnit.SECONDS));

        assertEquals(addedList.size(), Sets.newHashSet(addedList).size());
        assertEquals(removedList.size(), Sets.newHashSet(removedList).size());
    }

My last assertEquals fails with number of actual removed items more than unique items.

**Comment by nitsanw** [comment]
Verified the issue. Thanks for reporting and providing a test case.
Essentially the issue seems to be about this case:
https://github.com/JCTools/JCTools/blob/fe6d72a0f0ff0bd2c6412378c1231eef73539eed/jctools-core/src/main/java/org/jctools/maps/NonBlockingHashMap.java#L770-L770
```
// Actually change the Value in the Key,Value pair
    if( CAS_val(kvs, idx, V, putval ) ) {
      // CAS succeeded - we did the update!
      // Both normal put's and table-copy calls putIfMatch, but table-copy
      // does not (effectively) increase the number of live k/v pairs.
      if( expVal != null ) {
        // Adjust sizes - a striped counter
        if(  (V == null || V == TOMBSTONE) && putval != TOMBSTONE ) chm._size.add( 1);
        if( !(V == null || V == TOMBSTONE) && putval == TOMBSTONE ) chm._size.add(-1);
      }
    } else {                    // Else CAS failed
      V = val(kvs,idx);         // Get new value
      // If a Prime'd value got installed, we need to re-run the put on the
      // new table.  Otherwise we lost the CAS to another racing put.
      // Simply retry from the start.
      if( V instanceof Prime )
        return putIfMatch(topmap,chm.copy_slot_and_check(topmap,kvs,idx,expVal),key,putval,expVal);
    }
    // Win or lose the CAS, we are done.  If we won then we know the update
    // happened as expected.  If we lost, it means "we won but another thread
    // immediately stomped our update with no chance of a reader reading".
    return (V==null && expVal!=null) ? TOMBSTONE : V;
```
The NBHM is taking the view that if we lost the CAS we can return V which is the new observed value for this key. This is problematic here as several competing writes and removes to the same key can lead to reporting of the new value back multiple times.
In the write case the correctness of this is justified by the comment: "we won but another thread immediately stomped our update with no chance of a reader reading". This is fine, but I disagree with returning the new value. Surely we should fake success by returning the old value in this case?
In the remove case this leads to the issue you observe where potentially multiple removes have failed due to a concurrent write and all report back the same value as if they removed it. That is clearly incorrect and can detected fixed by checking if the `putval` is TOMBSTONE when we failed the CAS. I think for a `remove` the correct response however is less clear. If we accept your assumption in the test (which seems valid), returning the old value or the new value is incorrect here, and returning null indicates the key was missing which is also incorrect. We can retry the remove until we succeed in removing or the key is gone (as some other concurrent remove was successful).
@cliffclick please review the issue and chip in?

**Comment by cliffclick** [comment]
Yeah, I went round and round on this one a bunch (toe to toe with Doug 
Lea, bleah).  The core issue (for me anyways), is that the Java Unsafe 
CAS returns a pass/fail boolean, instead of a "witness" - the value on 
which the CAS failed.  Intel CAS hardware returns the witness.  Given 
that another thread can immediately change the value again, the 
"witness" is forever lost - a flaw in the Java CAS spec, as far as I am 
concerned - and this is the root cause of this issue.

The comments below are only partially correct.

After the CAS fails, there is "V = val(kvs,idx);" - which loads a "best 
guess witness as to why the CAS failed", but the actual witness is gone, 
gone, gone.

Having seen the CAS fail, having seen that we're not rolling to a new 
table, what do to next?

The writer suggests "Surely we should fake success by returning the old 
value in this case?"

*This is wrong, *since on success your value would be installed, and 
since the value changed, your value MUST have been returned to some 
other CAS - and it is not.  Hence the current (failing CAS) thread 
believes it "handed off" 'V' to the table and another thread will pick 
it up and take responsibility for it.  That didn't happen, *and leads to 
leaking 'V'*.  You cannot return success here.

Returning the "almost witness" is actually correct, and also cheap (and 
also fairly close to some kind of "perfect" semantics") and 
understandable - but it leads to this funny situation as noted by the 
author: "... and all report back the same value _/as if they removed it/_".
Italics are mine.
No!  They report back "this is the write we failed on".  Nothing got 
removed, since the CAS failed. /The remove failed/.

Basically the removing thread is busy fighting with an installing 
thread, and the outcome is guaranteed fuzzy.
And if some other thread is trying hard to install new values, do you 
really care that the remove failed?

Instead the sentence could read:

"In the remove case this leads to the issue you observe where 
potentially multiple removes have failed due to a concurrent write and 
all report back the same value /that caused all the removes to fail/."

Another course of action here might be to spin on remove (not in this 
function, but at a higher level) until something gets removed... which 
means some other writer thread which is busy furiously writing will 
eventually see the 'null' as the old value (which is not true if we 
report success on remove on a failed CAS).

Who should spin-on-failed-remove?

I voted that the library user should, but you could reasonably vote that 
the library itself should.


Cliff

**Comment by nitsanw** [comment]
Thanks @cliffclick 
The way I see it this issue boils down to the semantics of put(and remove by extension) on CM.
Should put have the semantics of a getAndSet? if so the only option we have is spinning here (or reworking the algo all together).
If not, then returning values have an unclear meaning as they cannot convey to the user the kind of failure that happened:
- null -> there was nothing in the map for key
- replaced value -> successful put
- ??? -> the value inserted was never inserted. Returning the old value is a way of saying "this is what I'd have replaced had I been successful, let's pretend I was" and returning the new value is a way of saying " this is the new value for now". Either way the user can't be expected to be able to reason about this.

It seems as though CHM as the reference implementation here errs on the side of getAndSet, and I think we should too. I'll frame the requirement as a unit test and see what we can see.

**Comment by cliffclick** [comment]
| "Either way the user can't be expected to be able to reason about this"

Yes, they can!  But not in the clean way returning the witness would allow.

You get "here's the last value I found there".  Sometimes that's good 
enough.
And sometimes you don't care and the looping check is just overhead 
(e.g. a table of hi-usage perf counters)

The alternative loops until success OR a value is returned which "looks 
like a witness".
It's NOT THE WITNESS, it's NOT THE REASON YOU FAILED.  It's just "coulda 
been the witness".

I hit at least one use-case where I actually didn't want the loop, and 
the return value is always no better than "here's what I found after a 
failure".

Not saying "don't go with getAndSet", just saying its not all that 
clear-cut

Cliff

**Comment by cliffclick** [comment]
No dummy volatile, no "newV".
Since the CAS failed, no need for ordering.
Any successful CAS on the recursive putIfMatch will get the required 
ordering.

Speaking of recursion, You Can't Do It Here.
This CAS might fail nearly indefinitely, leading to stack overflow.
The other places I do recursion all do it when the table size is 
doubling; you'll quickly run out of need for table (or memory) long 
before running out of stack.


Cliff

**Comment by cliffclick** [comment]
Nice tweet storm...  :-)

Happy to review a (non-recursive) patch?

Still on the fence personally about 
looping-or-returning-failed-non-witness, but willing to roll with "loop 
until have a witness-like thing or success".

Could be a J9-only version now, that returns the Actual Witness. Opens 
up a few more use cases.

:-)

Let me know what you want,
Cliff

**Comment by nitsanw** [comment]
"Yes, they can!  But not in the clean way returning the witness would allow."
I'm not clear how the user, in the case shown in the test, can be expected to know that they did not actually atomically swap newval for oldval. I don't think the API allows a way to convey this meaning. I can't find a clear documentation specifically for ConcurrentMap, so we have to take the Map javadoc:
"Associates the specified value with the specified key in this map (optional operation). If the map previously contained a mapping for the key, the old value is replaced by the specified value. Returns the previous value associated with key, or null if there was no mapping for key."

I think a user would intuitively expect the getAndSet guarantee, but an implementor could arguably read "the previous value" to mean "the value replaced" (getAndSet semantics) or "last value known to be there" (what the code currently does) or "the value we pretend to have replaced" (which would be the value at the time of the key CAS). I think the _getAndSet_ semantics are the right choice here, though they come at a price.

Where there's a win to be had with weaker guarantees we may want to consider offering another method. I'm still not sure how JDK9 only features will be supported within JCTools. I'm trying to keep the JDK6 crowd happy still.

"No dummy volatile, no "newV". Since the CAS failed, no need for ordering."
On further reading of the code I agree there's no need for the volatile read, but that is due to the successful key CAS after the read of V which would force a re-read from the array.

"Speaking of recursion, You Can't Do It Here."
Agreed, will fix it to loop instead.

Thanks for your feedback :-) I'll post another patch soon.

**Comment by nitsanw** [comment]
Updated patch: https://gist.github.com/nitsanw/992d4f48ff7066a8eb6c3f2a70fb5599

**Comment by cliffclick** [comment]
"..."the previous value" to mean "the value replaced" (getAndSet semantics)"


'The value replaced' is not available on a failed CAS. *Is not available 
under any circumstance... *without using the new J9 primitives.

"...or "the value we pretend to have replaced" "

This is problematic, because we didn't actually replace it, when the CAS 
failed.  The caller can reasonably assume the CAS succeeded - and 
therefore this thread can 'take responsibility' for the thing that got 
pulled out of the table - except that some OTHER thread DID succeed, and 
so ITS taking responsibility.

"(which would be the value at the time of the key CAS)"

... bad mistake.  It's not the value at the time of the key CAS. Might 
help to imagine the value field is a 'blur' - a dozen threads are 
changing it 1 million times a second; unreadable in any real sense, 
except that you get random probe of what those threads are setting it to.


" "last value known to be there" (what the code currently does)"

This only works if we ALSO report failure, along with the last value 
(which might match what we could have succeeded on).
   :-P

Cliff

**Comment by cliffclick** [comment]
Loop in wrong place, no need to re-loop the Key setup logic.
Also wrong: must test for a Prime on the loaded value (and recurse to 
new table), before loading again.

Try:

   while( true ) { // <<<<<<<<=====================
     // ---
     // Found the proper Key slot, now update the matching Value slot.  We
     // never put a null, so Value slots monotonically move from null to
     // not-null (deleted Values use Tombstone).  Thus if 'V' is null we
     // fail this fast cutout and fall into the check for table-full.
     if( putval == V ) return V; // Fast cutout for no-change

     // See if we want to move to a new table (to avoid high average re-probe
     // counts).  We only check on the initial set of a Value from null to
     // not-null (i.e., once per key-insert).  Of course we got a 'free' check
     // of newkvs once per key-compare (not really free, but paid-for by the
     // time we get here).
     if( newkvs == null &&       // New table-copy already spotted?
         // Once per fresh key-insert check the hard way
         ((V == null && chm.tableFull(reprobe_cnt,len)) ||
          // Or we found a Prime, but the JMM allowed reordering such that we
          // did not spot the new table (very rare race here: the writing
          // thread did a CAS of _newkvs then a store of a Prime.  This thread
          // reads the Prime, then reads _newkvs - but the read of Prime was so
          // delayed (or the read of _newkvs was so accelerated) that they
          // swapped and we still read a null _newkvs.  The resize call below
          // will do a CAS on _newkvs forcing the read.
          V instanceof Prime) )
       newkvs = chm.resize(topmap,kvs); // Force the new table copy to start
     // See if we are moving to a new table.
     // If so, copy our slot and retry in the new table.
     if( newkvs != null )
       return putIfMatch(topmap,chm.copy_slot_and_check(topmap,kvs,idx,expVal),key,putval,expVal);

     // ---
     // We are finally prepared to update the existing table
     assert !(V instanceof Prime);

     // Must match old, and we do not?  Then bail out now.  Note that either V
     // or expVal might be TOMBSTONE.  Also V can be null, if we've never
     // inserted a value before.  expVal can be null if we are called from
     // copy_slot.

     if( expVal != NO_MATCH_OLD && // Do we care about expected-Value at all?
         V != expVal &&            // No instant match already?
         (expVal != MATCH_ANY || V == TOMBSTONE || V == null) &&
         !(V==null && expVal == TOMBSTONE) &&    // Match on null/TOMBSTONE combo
         (expVal == null || !expVal.equals(V)) ) // Expensive equals check at the last
       return V;                                 // Do not update!

     // Actually change the Value in the Key,Value pair
     if( CAS_val(kvs, idx, V, putval ) ) break;  <<<==========  BREAK ON A WIN HERE
     // CAS failed.  Because we have no witness, we do not know why it failed.
     // Indeed, by the time we look again the value under test might have flipped
     // a thousand times and now be the expected value (despite the CAS failing).
     // Check for the never-succeed condition of a Prime value and jump to any
     // nested table, or else just re-run.
     V = val(kvs,idx);         // Get new value
     // If a Prime'd value got installed, we need to re-run the put on the
     // new table.  Otherwise we lost the CAS to another racing put.
     if( V instanceof Prime )
       return putIfMatch(topmap,chm.copy_slot_and_check(topmap,kvs,idx,expVal),key,putval,expVal);
     // Simply retry from the start.
    } <<========================== LOOP HERE

    // CAS succeeded - we did the update!
    // Both normal put's and table-copy calls putIfMatch, but table-copy
    // does not (effectively) increase the number of live k/v pairs.
    if( expVal != null ) {
      // Adjust sizes - a striped counter
      if(  (V == null || V == TOMBSTONE) && putval != TOMBSTONE ) chm._size.add( 1);
      if( !(V == null || V == TOMBSTONE) && putval == TOMBSTONE ) chm._size.add(-1);
    }
    // We won; we know the update happened as expected.
    return (V==null && expVal!=null) ? TOMBSTONE : V;
  }

**Comment by nitsanw** [comment]
"'The value replaced' is not available on a failed CAS. *Is not available under any circumstance... *without using the new J9 primitives."
The value replaced is ONLY available on a successful CAS, so while the J9 primitives might help you implement a more accurate failed "put", that is not part of implementing `getAndSet` semantics.

""(which would be the value at the time of the key CAS)" ... bad mistake.  It's not the value at the time of the key CAS."
It's the value we observed close to the key CAS, it's the value we believed to have been in the table when we CASed the value after a successful key CAS. Yes, it's fuzzy. In any case, not what we're going for.

"Loop in wrong place, no need to re-loop the Key setup logic. Also wrong: must test for a Prime on the loaded value (and recurse to new table), before loading again."
If we don't re-loop we need the special case for the value. If we do re-loop than we will check for it again after re-claiming the key slot.

Should we re-claim the key slot? chewing on that with my breakfast... will be back.

**Comment by cliffclick** [comment]
On 1/19/2018 11:37 PM, Nitsan Wakart wrote:
>
> "'The value replaced' is not available on a failed CAS. *Is not 
> available under any circumstance... *without using the new J9 primitives."
> The value replaced is ONLY available on a successful CAS, so while the 
> J9 primitives might help you implement a more accurate failed "put", 
> that is not part of implementing |getAndSet| semantics.
>
Yeah, ok.

> ""(which would be the value at the time of the key CAS)" ... bad 
> mistake. It's not the value at the time of the key CAS."
> It's the value we observed close to the key CAS, it's the value we 
> believed to have been in the table when we CASed the value after a 
> successful key CAS. Yes, it's fuzzy. In any case, not what we're going 
> for.
>
Sorry, didn't mean to be so harsh.  Yeah, it's fuzzy - not exact - was 
all I was saying.  Was worried you were falling into the "we can get the 
exact value this way" trap.

> "Loop in wrong place, no need to re-loop the Key setup logic. Also 
> wrong: must test for a Prime on the loaded value (and recurse to new 
> table), before loading again."
> If we don't re-loop we need the special case for the value. If we do 
> re-loop than we will check for it again after re-claiming the key slot.
>
> Should we re-claim the key slot? chewing on that with my breakfast... 
> will be back.
>
You already got the key slot, the "re-claim" will simply observe that 
you got it and fall into the next stanza.  You can never "unget" a key 
slot once gotten, except via the whole-table-copy semantics.

Me, I don't like the double-nested loop.  Obfuscates control flow too 
much.  Since you don't need to reclaim the key slot, don't loop over 
it.  Wasted brain cells (and very likely slightly slower code) - the 
next maintainer will always be asking "why are we retrying the key slot 
here?".

And I'd comment the dickens out of the value retry with a note about no 
witness prior to J9 forcing the loop here on all calls requiring the 
exact value on fail.



Cliff

**Comment by nitsanw** [comment]
"You already got the key slot, the "re-claim" will simply observe that you got it and fall into the next stanza.  You can never "unget" a key slot once gotten, except via the whole-table-copy semantics. "
Yes. Needed to re-read the key state transition again. Also agreed that nested loops makes for harder to read code.
Will commit soon.
Thanks for the help @cliffclick :-)

**Comment by nitsanw** [comment]
@cliffclick went with your recommendation, but added a read fence on the loop edge, otherwise the value load could be hoisted. Please review the commit.
Thanks @fvlad for catching this!

**Comment by cliffclick** [comment]
Yeah looks good!

Thanks

Cliff
