### ISSUE TITLE
Example for correct usage of queues

### ISSUE THREAD

**Issue by oobles** [JCTools/JCTools#213]
I've spent a bit of time today searching on the correct way to implement producer and consumer.  My absolutely rudimentary implementation is ok when data is flowing but terrible at edge cases of empty and full.  The producer side:  

```
while (!queue.offer(queueEntry)) {
   try {
      Thread.sleep(100);
   } catch( InterruptedException ex) {}
}
```
The consumer thread is just as ugly.  

```
while (true) {
   try {
      if (queue.isEmpty()) {
         try {
             Thread.sleep(SLEEP_TIME);
         } catch (final InterruptedException e) {}
      } else {
             ... do something useful.. reading queue until it is empty ...
      }
   } catch (final Throwable t) {
        LOG.error("EXCEPTION CAUGHT!", t);
     }
}
```

Obviously, if data is flowing and we're not full, great.  But the edge cases of a full queue and empty queue are not exactly elegant.  Interested in recommended or other ways to deal with the full and empty case.  The queue is bursty with times of lots of data flowing and other times of none. I suspect that even during bursty period threads are probably spending too much time sleeping.

**Comment by oobles** [comment]
A slightly better implementation based on the fact I really want to optimize waking up the consumer in the case of an empty queue.  In the case of a full queue, just back off slowly.

Producer:

```
if (queue.isEmpty()) {
     syncrhonized(queue) {
        queue.offer(queueEntry);
        queue.notify();
     }
} else {
     long wait = 10;
     while (!queue.offer(queueEntry)) {
     try {
           Thread.sleep(wait);
           if (wait < 1000) {
               wait += 10;
           } else {
                LOG.warn("queue full!");
           }
      } catch (final InterruptedException e) { }
}
```

Consumer: still has a thread waiting around per consumer.  A better solution might be to have an ExecutorService and submit work when queue changes from empty.

```
while (true) {
     try {
          if (queue.isEmpty()) {
               synchornized(queue) {
                   while(queue.isEmpty()) {
                      queue.wait(MAX_WAIT_TIME);
                   }
               }
          } else {
              ... do useful things here ...
          }
     } catch (final Throwable t) {
           LOG.error("UNEXPECTED EXCEPTION {}", t);
     }
}
```

**Comment by nitsanw** [comment]
How you choose to handle waiting for messages/space is not a correct usage question and is left to users to decide on. The users may choose to spin/yield/sleep, or they may choose to do other work. There's no general answer here. You could look at queues and log buffers usage in Aeron to get some ideas in the low latency space.
However, responding to your samples:
- It's faster to poll and check for null instead of checking isEmpty and then polling.
- Synchronizing on the queue seems like a bad idea, I recommend you use a separate monitor if that's the way you want to go.

You can use the fill/drain methods to avoid implementing your own loops, but that may not fit your usecase.
