### ISSUE TITLE
`NonBlockingHashSet` retains deleted values

### ISSUE THREAD

**Issue by ikhoon** [JCTools/JCTools#354]
`NonBlockingHashSet.remove(objectA)` does not remove the specified object from `_kvs` and retains a strong reference.
After removing, if a new object whose hash code is the same with `objectA` is added later, the removed value `objectA` is revived.
This behavior is different from JDK's `HashMap`.

For example:
```java
NonBlockingHashSet<MyEntry> endpoints = new NonBlockingHashSet<>();
MyEntry entry1 = new MyEntry(1, 1111); 
endpoints.add(entry1);
// 'remove()'  keeps the reference of `entry1` in `_kvs`
endpoints.remove(entry1);
MyEntry entry2 = new MyEntry(1, 2222); 
endpoints.add(entry2);

// entry1 is revived.
// JDK's HashMap clears entry1 and contains entry2
assert endpoints.toArray()[0] == entry1;

class MyEntry {
    int value;
    long updatedAt;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Entry)) return false;

        final Entry entry = (Entry) o;
        return value == entry.value;
    }

    @Override
    public int hashCode() {
        return value;
    }
}
```

**Comment by ikhoon** [comment]
As `NonBlockingHashSet` delegates to `NonBlockingHashMap`, the problem is also reproduced in `NonBlockingHashMap`
```
NonBlockingHashMap<MyEntry, String> map = new NonBlockingHashMap<>();
map.put(entry1, "a");
map.remove(entry1);
map.put(entry2, "a");
// entry1 is revived.
assert map.keySet().toArray()[0] == entry1;
```

**Comment by nitsanw** [comment]
The issue here is that:
1. NBHM retains deleted **keys** (values in the set). This is a potential GC issue, but is inherent to the implementation.
2. `MyEntry` is not a good key

Your code asserts that 2 entries are equal if the `value` is the same, ignoring `updatedAt`. NBHM therefore treats them as such and will not replace the reference to the first key with the second.

**Comment by nitsanw** [comment]
I'm closing, please comment if you feel this is breaking the `Map` API somehow.

**Comment by ikhoon** [comment]
> please comment if you feel this is breaking the Map API somehow.

Yes, I think so. It is unexpected behavior and causes bugs in our project.

`MyEntry` is an intentional example to reproduce the problem. [We](https://github.com/line/armeria) provide [`Endpoint`](https://github.com/line/armeria/blob/bcb621e46c26f0ac84b4b820687383a99b509019/core/src/main/java/com/linecorp/armeria/client/Endpoint.java#L61) that represents a remote host and port. In addition to host and port, `Endpoint` also has weight property for client-side load balancing.
`Endpoint` excludes the additional property - weight from `equals` and `hashCode` for better comparison of remote peers. 
https://github.com/line/armeria/blob/bcb621e46c26f0ac84b4b820687383a99b509019/core/src/main/java/com/linecorp/armeria/client/Endpoint.java#L666-L668

We used `NonBlockingHashSet` for [maintaining healthy endpoints](https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java#L121). When a weight of a endpoint is changed, we need to remove the old endpoint and add the new endpoint. 
However, `NonBlockingHashSet` did now replace the old endpoint with the new endpoint even though I called `remove` and `put` explicitly. 
https://github.com/line/armeria/pull/3927/files#diff-4229d073a6969fa85c1d6fe69c6c3d1c957a6a240dd77e3e397b3bf4c96792f0
```diff
- final Set<Endpoint> healthyEndpoints = new NonBlockingHashSet<>();
+ final Set<Endpoint> healthyEndpoints = ConcurrentHashMap.newKeySet();
```

**Comment by nitsanw** [comment]
@ikhoon I understand your frustration. I don't think this is an issue that we can easily fix within the confines of the current implementation however.
* NBHM hangs on to deleted keys until resize.
* NBHM will not overwrite key (deleted or otherwise) with a new key which is equal to it on `put`.

Changing this latter behaviour will slow down all operations on map by adding more code to a critical path which is already crowded. It can be done (by specialising behaviour on previous value being `TOMBSTONE` and key being equal), but I would need a strong argument from `Map`/`Set` documentation which clearly shows this behaviour to be wrong.

**Comment by ikhoon** [comment]
Thanks for your consideration. As I knew the expected behavior of NBHM, I can carefully use it. Mentioning this behavior in Javadoc would be super helpful for users. 🙇‍♂️
