### ISSUE TITLE
Evaluate an spsc circular linked node queue

### ISSUE THREAD

**Issue by ChristianWulf** [JCTools/JCTools#52]
Allocate n nodes at the beginning just like we do with an array and linked the last with the first node. In contrast to the array version, we do not need to manage any indices and do not need to compute an offset. We just need to sync the node value via soValue and lvValueAndNull. Next is fixed in a bounded version. I do not know how the cache locality could break the performance here since we do not use an array.

**Comment by nitsanw** [comment]
I doubt this is going to work:
- What do you lose? predictable stride, reference density, false sharing protection on reference array. Consider the size of the queue you propose is sizeof(Node) * size. The Node size will likely be 16-24 bytes (2 ref fields + header), this is compared to 4-8b per ref in an array(+array header/padding which is overhead for the whole array so averaged on all elements).
- What do you win?
"we do not need to manage any indices and do not need to compute an offset" - chasing references is far more expensive than computation. What's more is that you are trading setting the index for setting the head/tail reference. Reference fields read/writes are more expensive than primitives because of oop accounting(compressed oops/card marking).
