### ISSUE TITLE
SpscUnboundedArrayQueue state corruption

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#75]
The following loop checks small queues. With the master version, it prints unexpected values for capacity 1, 2 and 4. (The program simply offers capacity + 1 element and then tries to poll each back.)

```java
for (int i = 1; i <= 32; i *= 2) {
    System.out.println("-- " + i);
    SpscUnboundedArrayQueue<Integer> queue = new SpscUnboundedArrayQueue<Integer>(i);

    for (int j = 0; j <= i; j++) {
        queue.offer(j);
    }
    for (int j = 0; j <= i; j++) {
        Integer v = queue.poll();
        if (v == null || v != j) {
            System.out.printf("%d| expected: %d, actual:%d%n", i, j, v);
        }
    }
}
```
Output:
```
-- 1
1| expected: 0, actual:1
1| expected: 1, actual:null
-- 2
2| expected: 0, actual:2
2| expected: 2, actual:null
-- 4
4| expected: 0, actual:4
4| expected: 4, actual:null
-- 8
-- 16
-- 32
```
I think the problem is in the interplay between [L129](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/SpscUnboundedArrayQueue.java#L129) and the lookahead calculation/epxectations.

This problem is present in the `SpscUnboundedAtomicArrayQueue` as well.

**Comment by nitsanw** [comment]
Looking at it. It seems the look ahead logic really doesn't work for buffer size < 8.
If it's less than 4 the step is 0, which is broken.
If it's 4 the step is 1, which in the SpscArrayQueue case is ok, but here we need to keep room for one extra element in the queue.
Since it's counter productive to set the chunk size so low I think the simplest fix is to throw an IllegalArgumentException.
In fact the whole look ahead logic is counter productive when the look ahead step is very very small, so I'm tempted to set a minimum size of 128 on the SpscArrayQueue/Growable/Unbounded buffers, leading to saner look ahead steps as well. Thoughts?

**Comment by akarnokd** [comment]
I see the following options:

  - Set the capacity to at least 8 in the constructor.
  - Throw IAE
  - Throw IAE and have a no lookahead implementation
  - Have a check in offer for capacity < 8 and do logic without lookahead.
