### ISSUE TITLE
Primitive-typed queues

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#78]
I've been playing with a C# port of our RxJava 2.0 library and run into a small feature mismatch with C#, namely that they can use primitives as generic type arguments and as such, I wasn't able to make primitives nullable in the Java sense for `SpscArrayQueue` for example.

My guess is that if I want, for example a `SpscIntArrayQueue`, I have to "waste" an int slot in the array just to indicate its adjacent field is empty.

What do you think?

**Comment by nitsanw** [comment]
Simplest solution is to revert to an index based empty check instead of the null check. See this queue:
https://github.com/JCTools/JCTools/blob/master/jctools-experimental/src/main/java/org/jctools/queues/SpscOffHeapIntQueue.java

If you want to go for a Fast Flow like queue you'll need a marker in the data stream:
You can pick a 'null value' or have the user provide one. Otherwise you can use a byte array to mark the slots on.
You could use a bitset + special value to reduce size. This means theres a pre-configured value marking as null and a special bitset which is marked when the special value is inserted removed. The common case would be fast and the slow case would require marking the bitset.

**Comment by akarnokd** [comment]
Thanks!
