### ISSUE TITLE
RFE: Add NonBlockingHashMap and friends (formerly known as high-scale-lib)

### ISSUE THREAD

**Issue by vyazelenko** [JCTools/JCTools#87]
It seems that this project would an ideal place to have `NonBlockingHashMap` created by @cliffclick. Unfortunately original project that was hosted on SourceForge (https://sourceforge.net/projects/high-scale-lib/) is dead and has been for quite a while. Also it is buggy, see stephenc/high-scale-lib#5 for one such example.

The current version of `NonBlockingHashMap` and supporting classes is available in the https://github.com/h2oai/h2o-3/ project under [`water.nbhm` package] (https://github.com/h2oai/h2o-3/tree/master/h2o-core/src/main/java/water/nbhm). 

The problem with those classes being part of https://github.com/h2oai/h2o-3 project is that it is hard to consumer this project as library since one needs to always exclude transitive dependencies and consume full jar with other classes. Another much bigger problem is that recently NBHM classes become more and more specialized for H2O use cases. In fact it seems that it is no longer possible to use those classes standalone (see https://github.com/h2oai/h2o-3/commit/6ef6f834e67585c55ed6c8b48817749d2643607e).

Hence this feature request asks to add awesome NBHM classes to this awesome JCTools project. 

/cc @cliffclick

**Comment by guidomedina** [comment]
You might want to also take a look at https://github.com/ben-manes/concurrentlinkedhashmap and ConcurrentHashMapV8 (Shipped with Java and ported back by some API), maybe the old concerns are long gone., Doug Lea did a nice job with V8 AFAIK.

**Comment by guidomedina** [comment]
Sorry, Ben Manes migrated `ConcurrentLinkedHashMap` to new project https://github.com/ben-manes/caffeine

**Comment by vyazelenko** [comment]
My primary use case is `NonBlockingHashMapLong` which avoids boxing during `get` and `put` operations. It is a big deal. At least until Java 10+.

**Comment by guidomedina** [comment]
I see, squashing as much as possible to minimize GC? or actual performance?

**Comment by vyazelenko** [comment]
Well, minimized GC and hence performance gains. But also on a storage side it's a nice gain. Thanks for the links.

**Comment by guidomedina** [comment]
Hmm, I still exhort you to take a look at these benchmarks: https://github.com/ben-manes/caffeine/wiki/Benchmarks

**Comment by nitsanw** [comment]
I will have a look at this. I played around with NHBM before and was planning to start out with a single writer variant (much simpler to implement). Importing code from other repositories requires some investigation into licencing etc.
As always PRs speak louder than issues! a PR with the NHBM map would be a great start.

**Comment by cliffclick** [comment]
Let me take a look, I made various minor fixes to NBHM in the H2O code 
base, but sounds like it needs a home outside of either source forge or H2O

Cliff

**Comment by guidomedina** [comment]
I'm wondering about CHMv8 new functionalities like computeIfPresent/computeIfAbsent, are you guys making a Java 8 version of it?

**Comment by RichardWarburton** [comment]
There are default methods implementing all new Java 8 methods on `Map`, so it will be present even if the NBHM isn't updated.

**Comment by mjpt777** [comment]
@RichardWarburton Are the default methods designed to be concurrent? Last time I looked they were not and I think people's expectations of NBHM would be that.

**Comment by guidomedina** [comment]
I just looked at the CHMv8 and it overrides both functions making it concurrent with locking and default implementation of ConcurrentMap interface cycles CPU so both are concurrent if you ask me, but it is always easy from an IDE to take a look by yourself ;-)

**Comment by mjpt777** [comment]
@guidomedina That is what I could expect. My concern would be copying over NBHM from H2O without adding those.

**Comment by guidomedina** [comment]
Is NBHM a subclass of ConcurrentMap? if yes then it will be concurrent, is a subclass of Map only, then it will not be concurrent.

**Comment by RichardWarburton** [comment]
From a quick look at the implementation I agree with @guidomedina. The default method implementations in `ConcurrentMap` are thread-safe, but assume that you have a map that can't contain `null` values. The ones you just inherit from `Map` aren't, from a quick eyeball for example `computeIfAbsent` on Map can compute even if the value is present in the concurrent case.

**Comment by guidomedina** [comment]
@RichardWarburton yes but you need to look at `ConcurrentMap` interface default methods, they differ from the ones from `Map` as they should.

**Comment by RichardWarburton** [comment]
Hi @guidomedina, apologies for not being clearer in my previous comment. I did look at them and concluded that the ConcurrentMap ones are fine to inherit - as long as you don't allow null values.

**Comment by guidomedina** [comment]
Have you guys JMH CHMv8 vs NBHM, specifically using Java 8u40+ (While at it just go for Java 8u74)

**Comment by nitsanw** [comment]
Benchmarking concurrent maps is tricky business and the performance will depend on your app/data set/hardware. I've got some ideas in that direction, but not had time to fully expand them.

**Comment by guidomedina** [comment]
Maybe we can use Ben's Caffeine JMH code and add NBHM, I'm sure he won't oppose to the idea of another CHM with his JMH code, in fact, it might be even a PR onto his project which measures Caffeine, Guava, CHMv8 and CLHM:

https://github.com/ben-manes/caffeine/tree/master/caffeine/src/jmh/java/com/github/benmanes/caffeine

**Comment by ben-manes** [comment]
NBHM is a [supported](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/CacheType.java#L63) unbounded type, but isn't in the default param list. The reason is because Cliff short-circuits writes to no-op when updating an entry to the same value. This is a fine optimization, but is misleading as the benchmark shows throughput on a 100% hit rate with a zipf distribution to emulate real-world contention. Doug's maps are pessimistic, requiring that I prescreen the cache's compute methods to avoid lock contention, though this becomes a non-issue on a 32+ core machine.

I don't think my benchmarks would show a fair comparison on write workloads, but perhaps could be adapted. Cliff `PerfHashBenchmark` may also be worth reviewing, though it predates JMH. It is important to understand the design of the different implementations to ensure one doesn't skew the results by unintentionally exploiting a characteristic that may not match common behavior.

Last I recalled Doug said that the two performed on par for most workloads, with each winning in some cases. The concurrent table resize and compactness (improved key cache locality) were wins for NBHM, though it could suffer from CAS storms. I suspect Cliff and Doug are the right people to put benchmarks together to be a fair judge, and probably both already know the special cases of when to prefer one over the other.

But I think most users would be unaffected by the difference, so details like primitive specialization or atomic computes would be the most important details for considering which to use. I'd be concerned that @nitsanw might be over burdened if he took on maintenance given how the JDK is progressing, so H2O splitting their revision into a semi-maintained repo would be best imho.

**Comment by nitsanw** [comment]
closing as duplicate of #88
